egrep > grep

diff --git a/{{cookiecutter.out_dir}}/.gitlab-ci.yml b/{{cookiecutter.out_dir}}/.gitlab-ci.yml
--- a/{{cookiecutter.out_dir}}/.gitlab-ci.yml
+++ b/{{cookiecutter.out_dir}}/.gitlab-ci.yml
@@ -188,7 +188,7 @@ before_script: &top_before_script
      dockerregistertag ${1}     ${DOCKER_REGISTRY}/${DOCKER_IMAGE}:${2}
      dockerregistertag ${1}-dev ${DOCKER_REGISTRY}/${DOCKER_IMAGE}:${2}-dev
    }
-   is_testable() { if ( echo "${CI_COMMIT_REF_NAME}" | egrep -q "${SKIP_TEST_BRANCHES}" );then return 1;fi;return 0; }
+   is_testable() { if ( echo "${CI_COMMIT_REF_NAME}" | grep -E -q "${SKIP_TEST_BRANCHES}" );then return 1;fi;return 0; }
    addregcacert() {
     if !( update-ca-certificates --help >/dev/null 2>&1 );then
       apk add --no-cache ca-certificates
@@ -218,7 +218,7 @@ before_script: &top_before_script
     set -e
     for f in ${AFTER_STATUS_FLAGS-};do
       f=$(eval echo ${f});t=${AFTER_STATUS_TIMEOUT} vwait_ready wait_flags "${f}"
-      if ( egrep -v 0 "${f}" );then exit $(cat "${f}");fi
+      if ( grep -E -v 0 "${f}" );then exit $(cat "${f}");fi
     done
     for f in ${AFTER_ALLOW_FAILURE_STATUS_FLAGS-};do
       f=$(eval echo ${f});t=${AFTER_STATUS_TIMEOUT} vwait_ready wait_flags "${f}"
@@ -241,7 +241,7 @@ before_script: &top_before_script
   set -e
   for f in ${BEFORE_STATUS_FLAGS-};do
     f=$(eval echo ${f});t=${BEFORE_STATUS_TIMEOUT} vwait_ready wait_flags "${f}"
-    if ( egrep -v 0 "${f}" );then exit $(cat "${f}");fi
+    if ( grep -E -v 0 "${f}" );then exit $(cat "${f}");fi
   done
   for f in ${BEFORE_ALLOW_FAILURE_STATUS_FLAGS-};do
     f=$(eval echo ${f});t=${BEFORE_STATUS_TIMEOUT} vwait_ready wait_flags "${f}"
@@ -256,7 +256,7 @@ before_script: &top_before_script
 - &linkapt set -e;if [ -e /var/cache/apt ];then rm -rf /var/cache/apt/archives;ln -s ${PROJECT_CACHE_ROOT}/apt /var/cache/apt/archives;fi
 - &settz ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo ${TZ} > /etc/timezone
 - &pullsubmodules
-    if !( echo ${GIT_SUBMODULE_STRATEGY-} | egrep -q none );then
+    if !( echo ${GIT_SUBMODULE_STRATEGY-} | grep -E -q none );then
     set -e;if ! (git --version >/dev/null 2>&1);then apk update;apk add git;fi &&
     cd ${PROJECT_COMMON_DEPLOY_DIR};( git fetch --unshallow  >/dev/null 2>&1 || true );git config remote.origin.fetch "+refs/heads/*:refs/remotes/origin/*";git fetch origin;git reset --hard $DJANGO_DEPLOY_VERSION --;cd - >/dev/null 2>&1;
     fi
@@ -454,7 +454,7 @@ services_tower: &services_tower
   - *cleanupstatusflag
   script:
   - *definefuncs
-  - &writeservivestohosts egrep "\s+(dockerregistries|docker)" /etc/hosts>"${COMMONHOSTSFILE}"
+  - &writeservivestohosts grep -E "\s+(dockerregistries|docker)" /etc/hosts>"${COMMONHOSTSFILE}"
   - &waitforservices
     set -e
     && t=${REGISTRIES_TIMEOUT:-180} vwait_ready wait_registries
@@ -548,8 +548,8 @@ services_tower: &services_tower
 {{docscomment}}      vv docker inspect ${BUILDCACHE_CURRENT_DOCKER_IMAGE_DOCS} >/dev/null
 {{docscomment}}      vv docker tag ${BUILDCACHE_CURRENT_DOCKER_IMAGE_DOCS} ${BUILDCACHE_DOCKER_IMAGE_DOCS}
 {{docscomment}}      vv docker tag ${BUILDCACHE_CURRENT_DOCKER_IMAGE_DOCS} ${BUILDCACHE_REF_DOCKER_IMAGE_DOCS}
-{{docscomment}}      ( echo $CI_COMMIT_REF_NAME | egrep -q "$TAGGUABLE_IMAGE_BRANCH$" ) && vv retry_cmd docker push ${BUILDCACHE_DOCKER_IMAGE_DOCS}
-{{docscomment}}      ( echo $CI_COMMIT_REF_NAME | egrep -q "^$MAIN_BRANCH$") && vv retry_cmd docker push ${BUILDCACHE_REF_DOCKER_IMAGE_DOCS}
+{{docscomment}}      ( echo $CI_COMMIT_REF_NAME | grep -E -q "$TAGGUABLE_IMAGE_BRANCH$" ) && vv retry_cmd docker push ${BUILDCACHE_DOCKER_IMAGE_DOCS}
+{{docscomment}}      ( echo $CI_COMMIT_REF_NAME | grep -E -q "^$MAIN_BRANCH$") && vv retry_cmd docker push ${BUILDCACHE_REF_DOCKER_IMAGE_DOCS}
 {{docscomment}}  - &docs_build ./docs/build.sh
 {{docscomment}}  - &docs_save tar czf "${DOCS_TARBALL}" ${DOCS_FOLDERS}
 {{docscomment}}  - *writeokstatus
@@ -602,7 +602,7 @@ build_images: &build_images
             dcadd=1
           fi
           if [ "x${dcadd}" != "x" ];then
-            if ( echo "${cfgs}" | egrep -q -- '-dev.yml' );then
+            if ( echo "${cfgs}" | grep -E -q -- '-dev.yml' );then
               echo "      - \"${img}-dev\"" >> ${dcoverrides}
             else
               echo "      - \"${img}\"" >> ${dcoverrides}
@@ -685,7 +685,7 @@ build_images: &build_images
     export f=${CI_PROJECT_DIR}/releasedimgs
     set -e
     cache_tags="$(eval echo '"(${CACHEABLE_BUILD_BRANCH:-${TAGGUABLE_IMAGE_BRANCH}}|${EXTRA_DOCKER_TAGS})(${IMAGE_FLAVORS})?"')$"
-    if ( echo ${CI_COMMIT_REF_NAME} | egrep -q "$TAGGUABLE_IMAGE_BRANCH$" ) || ( echo ${CI_COMMIT_REF_NAME} | egrep -q "${cache_tags}" );then cat>>${f}<<EOF
+    if ( echo ${CI_COMMIT_REF_NAME} | grep -E -q "$TAGGUABLE_IMAGE_BRANCH$" ) || ( echo ${CI_COMMIT_REF_NAME} | grep -E -q "${cache_tags}" );then cat>>${f}<<EOF
     ${BUILDCACHE_CURRENT_DOCKER_IMAGE}-dev         ${BUILDCACHE_REF_DOCKER_IMAGE}-dev
     ${BUILDCACHE_CURRENT_DOCKER_IMAGE}             ${BUILDCACHE_REF_DOCKER_IMAGE}
     EOF
@@ -697,7 +697,7 @@ build_images: &build_images
     EOF
     fi
     #
-    if ( echo ${CI_COMMIT_REF_NAME} | egrep -q "$TAGGUABLE_IMAGE_BRANCH$" );then cat>>${f}<<EOF
+    if ( echo ${CI_COMMIT_REF_NAME} | grep -E -q "$TAGGUABLE_IMAGE_BRANCH$" );then cat>>${f}<<EOF
     ${BUILDCACHE_CURRENT_DOCKER_IMAGE}-dev         ${REF_DOCKER_IMAGE}-dev
     ${BUILDCACHE_CURRENT_DOCKER_IMAGE}             ${REF_DOCKER_IMAGE}
     EOF
@@ -716,14 +716,14 @@ build_images: &build_images
     log "Pushing release file:"
     cat ${f} >&2
     ret=$(mktemp)
-    for i in "$(awk '"'"'{print $2}'"'"' ${f}|egrep    -- ${BUILDCACHE_REGISTRY})" \
-             "$(awk '"'"'{print $2}'"'"' ${f}|egrep -v -- ${BUILDCACHE_REGISTRY})";do
+    for i in "$(awk '"'"'{print $2}'"'"' ${f}|grep -E    -- ${BUILDCACHE_REGISTRY})" \
+             "$(awk '"'"'{print $2}'"'"' ${f}|grep -E -v -- ${BUILDCACHE_REGISTRY})";do
       imgs=$(eval echo ${i});(for img in ${imgs};do vv retry_cmd docker push ${img};echo "$? ${img}">>${ret};done)&
     done
     wait
     log "END push:"
     cat ${ret}
-    if [ "$(egrep -v ^0 $ret|wc -l)" != "0" ];then exit 1;fi'
+    if [ "$(grep -E -v ^0 $ret|wc -l)" != "0" ];then exit 1;fi'
   - *writeokstatus
   - *waitafterjobs
   variables: &release_vars
@@ -787,7 +787,7 @@ teardown_workspace: &teardown_workspace
     : "We use a workaround for tag deletion see https://github.com/regclient/regclient/blob/ee6331/regclient/tag.go#L82"
     for repo in $(rcu _catalog|jq -r .repositories[] );do for t in $(rcu ${repo}/tags/list|jq -r .tags[] 2>/dev/null|sort -V);do
       rimg=${repo}:${t};dimg=${BUILDCACHE_REGISTRY}/${rimg}
-      if ! (echo ${t} | egrep -q "${cache_tags}") || [ "x${CLEANUP_ALL_TAGS}" != "x" ];then
+      if ! (echo ${t} | grep -E -q "${cache_tags}") || [ "x${CLEANUP_ALL_TAGS}" != "x" ];then
         digest=$( ( rcu ${repo}/manifests/${t} -vX HEAD \
                         -H "Accept: application/vnd.docker.distribution.manifest.v2+json" 2>&1 \
                         | grep 'docker-content-digest:' | awk '{print $3}' ) || true )
@@ -1009,7 +1009,7 @@ promote_single_env: &promote_single_env
 {{teleportcomment}}    if ! (echo "using orig: ${orig:?orig has to be defined and not null}" >&2 );then ret=1;fi
 {{teleportcomment}}    if ! (echo "using dest: ${dest:?dest has to be defined and not null}" >&2 );then ret=1;fi
 {{teleportcomment}}    if ! (echo "using TELEPORT_MODE: ${TELEPORT_MODE:?has to be defined and not null}" >&2 );then ret=1;fi
-{{teleportcomment}}    if ! (echo ${TELEPORT_MODE}|egrep -q "$TELEPORT_MODES");then echo invalid TELEPORT_MODE;ret=1;fi
+{{teleportcomment}}    if ! (echo ${TELEPORT_MODE}|grep -E -q "$TELEPORT_MODES");then echo invalid TELEPORT_MODE;ret=1;fi
 {{teleportcomment}}    if [ "x${ret-}" != "x" ];then exit 1;fi
 {{teleportcomment}}  - &teleport |-
 {{teleportcomment}}    set -e;.ansible/scripts/call_ansible.sh -vv .ansible/playbooks/teleport.yml \
